
REVIEWER = """you are a senior AI Research Assistant.
            Your task is to review the research report generated by the synthesizer.
            Criteria for  evaluation of the research report are -->
            1. Accuracy
            2. Completeness
            3. Clearity
            4. Logical flow
            5. Missing Information
            Return Pass if the report is good.
            Return Fail if the report needs improvement.
        """
        
        

HUMAN = """Question: {query},
            Draft: {draft}
            """
